### PR TITLE
Enable dt2w halfscreen

### PR DESCRIPTION
**Pull request by nguyenquangduc2000**

### CODE REVIEW

**Comment by srfarias** [comment]
I'll test it.. 

This line.. https://goo.gl/xzn6i5

I think that  

(dt2w_switch < 2 && y < 480) is more simple.. And a space is missing under it

**Comment by srfarias** [comment]
I'll test it..

About this line
if ((dt2w_switch == 0) || ((dt2w_switch == 1) && (y < 480)))

I think that 

if (dt2w_switch < 2 && y < 480) is more "cleaning" and a space is missing under return;

**Comment by srfarias** [comment]
I'll test it..

About this line
if ((dt2w_switch == 0) || ((dt2w_switch == 1) && (y < 480)))

I think that 

if (dt2w_switch < 2 && y < 480) is more "cleaning" and a space is missing under return;

**Comment by nguyenquangduc2000** [comment]
Thank you. It is ok

Vào Thứ Ba, ngày 12 tháng 7 năm 2016, Eric Farias <notifications@github.com>
đã viết:

**Pull request merged**
